### ISSUE TITLE
themes/socialbase/components/theme needs README

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/open_social#143]
In the themeing README.md you are revering to a README that doesn't exist:

> - The simple way
>   In case you want to use the default layout and components provided, it is very easy to get started.
>   In the components folder you can find a folder called theme. You can add your variable overrides here. More is explained in the readme file there.

There is no readme in themes/socialbase/components/theme

**Comment by MaikelGG** [comment]
Hi @spoetnik thanks for remark. Indeed this info is outdated. The setup I had created before is not future proof, so you can just create a subtheme and set socialbase as basetheme. Then you can either add your own library, or you can replace /extend libraries from the socialbase theme the drupal8 way.

**Comment by peterpolman** [comment]
@spoetnik Hi! We'd like to close this issue:)

In beta-9 we implemented the new theme architecture containing the bare socialbase theme and the branded socialblue theme which will provide a more extendable environment for themers. We provided readme's in these themes.

You can extend and override the libraries in these themes the D8 way. Our new styleguide/"component library" is available on: http://styleguide.getopensocial.com and we removed the old prototype since this got deprecated.
