### ISSUE TITLE
Missing mysql command in the application container

### ISSUE THREAD

**Issue by johnreytanquinco** [goalgorilla/open_social#328]
Minishift version: 1.0.0-beta.5

I am currently in loop with this problem. I am trying to install OpenSocial using this git repo.

This is the steps I followed to reproduce.
1. Installing the template in the server
`$ oc new-app https://github.com/goalgorilla/open_social -l name=social`

2. Expose the route
`$ oc expose service opensocial`

3. Creating the database container
`oc new-app mysql -e MYSQL_USER=drupal -e MYSQL_PASSWORD=drupal -e MYSQL_DATABASE=drupal --name=mysqlsocial`

4. Create PVC and run `$ gofabric8 volumes` to create PV.

5. Attached the storage to opensocial deployment

6. Install using composer. Since $PATH is not properly set on the container application I use the this command.
`$ php composer.phar install`

7. Update composer
`$ php composer.phar update --with-dependencies`

**ISSUE**
- Drush is not installed/included in the Drupal container application.
- Mysql is also not installed/included in the Drupal container application.

**FIXED**
- Added Drush line below in composer.json and rerun step#7. Drush is now installed.
     `"drush/drush": "8.*@stable"`
 
**CURRENT ERROR**
Now when I try to use drush to install the site and connect to database with the following command:
```
$ php /opt/app-root/src/vendor/drush/drush/drush -v -y site-install social --db-url=mysql://drupal:drupal@mysqlsocial/drupal --site-name=Op
enSocial
```

I am getting this error message, saying mysql command is not found.
```
Executing: mysql --defaults-extra-file=/tmp/drush_HukVis --database=drupal --host=mysqlsocial --silent  < /tmp/drush_UMzh7v > /dev/null          
You are about to create a /opt/app-root/src/sites/default/settings.php file and CREATE the 'drupal' database. Do you want to continue? (y/n): y
Sites directory /opt/app-root/src/sites/default already exists - proceeding.
Executing: mysql --defaults-extra-file=/tmp/drush_nHBFRx --database=drupal --host=mysqlsocial --silent  < /tmp/drush_4h1g5u > /dev/null          
Executing: mysql --defaults-extra-file=/tmp/drush_8Q3itD --database=information_schema --host=mysqlsocial --silent  < /tmp/drush_DWLsFA
Failed to create database: sh: mysql: command not found
Command dispatch complete
```

**ATTEMPT**
Using `$ echo $PATH` and `$ find . -name mysql` . I try to locate it but there is no mysql client. Only mysql_config is showing under /usr/bin.

Is there any way we can include mysql client in the composer file?

**Comment by jaapjan** [comment]
Hi! 

I suggest to check out the installation instructions here: https://github.com/goalgorilla/drupal_social/wiki/Installing-and-updating

Also we've created a composer [project template ](https://github.com/goalgorilla/social_template/) for installation of open_social. You should use this one since that will already install drush and all the required application dependencies. 

There is no way to include the mysql client in the composer file. I think we should separate the hosting set-up from the application as much as possible. Will close this issue for now, but feel free to create a new issue on [drupal.org/project/social](https://drupal.org/project/social) if you have any other questions.
